### ISSUE TITLE
Can't join party game

### ISSUE THREAD

**Issue by Windfisch** [Gjum/agarnet#11]
When trying to join a party game with latest agarnet library and latest Windfisch/agario-frickel bot, this won't work.
Instead, I am getting an OS error (invalid argument) when connecting to the socket.

Inserting a `print(self.address)` in agarnet/client.py, Line 88, we see that it tries to connect to an address called "1". This is obviously not correct.

Checkout the agarnetbug2 branch of https://github.com/Windfisch/agario-frickel, create a party game and run `python main.py [PARTYTOKEN]`.

Expected result: an agario-alike window opens, the bot actually works.

Actual result: The following stacktrace:

```
flo@midna ~/agario2 $ python main.py X87JS
trying to connect, attempt 1
using party token
1   <---- this is the output from the print(self.address) statement inserted into client.py
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    c.connect(addr,token)
  File "/home/flo/agario2/agarnet/agarnet/client.py", line 90, in connect
    self.ws.connect('ws://%s' % self.address, origin='http://agar.io')
  File "/usr/lib64/python3.4/site-packages/websocket/_core.py", line 430, in connect
    self.sock.connect(address)
OSError: [Errno 22] Invalid argument
```

**Comment by Gjum** [comment]
Seems to be working fine on my end. Maybe just a temporary issue?

**Comment by Windfisch** [comment]
Have you tried the agarnetbug2 branch and a freshly generated party token? It still doesn't work for me.

I am using python3.4, maybe this is the problem?

**Comment by Gjum** [comment]
I did this:

``` python
_, token = find_server(mode='party')
address = get_party_address(token)
```

It connects fine, and I can also connect with the official client (twice).

Also using Python 3.4

**Comment by Gjum** [comment]
I just tried this, which I think is is what your client does, and it's also working:

``` python
    token = '5AQHU'  # generated with official client
    address = get_party_address(token)
```

I connected with `gagar` twice at the same time, both successful.

**Comment by Windfisch** [comment]
ahh, i did `address, *_ = get_party_address(token)`, which decomposed the string. Some day, get_party_address must have returned a tuple, which is why this has once worked.

So I was only holding it wrong, sorry ;)

**Comment by Gjum** [comment]
Ah yes, I changed that in 0.2.0 I guess. Sorry for not writing a proper changelog!
