### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Windfisch** [Gjum/agarnet#5]
agarnet could use some documentation which is more than "Use the (library) Source, Luke".

in Windfisch/agario-frickel@c5bc7da in test.py there is a _really_ basic demo client, which covers all the game features in ~60 Lines of Code (plus the Subscriber class stub).

(the later revisions will add more and more features that are not necessary for understanding the agarnet lib)

Maybe this already helps for documentation purposes. Feel free to use/adapt it.

**Comment by Gjum** [comment]
Yeah, a minimal example would be really cool. I also started to write some tests, they (do/will/should) also cover some basic usage.

**Comment by Gjum** [comment]
Started here: https://github.com/Gjum/agarnet/tree/master/doc

**Comment by Gjum** [comment]
I'm not documenting `buffer` and `vec`. `gcommer` is documented with docstrings already.
