### ISSUE TITLE
Strange behaviour when accessing world.cells in on_cell_eaten() callback.

### ISSUE THREAD

**Issue by Windfisch** [Gjum/agarnet#7]
when trying to get some information about the eater cell within the on_cell_eaten() callback, like so:

``` python
     def on_cell_eaten(self, eater_id, eaten_id):
        if self.c.world.cells[eater_id].is_virus:
             print("virus ate something!")
```

then the read(!) access automatically creates a new dict entry, if `eater_id not in self.c.world.cells`, causing weird behaviour in my application.

Why is `world.cells` a `defaultdict(Cell)` and not a normal `dict`? I think it would be better to make it a normal `dict`, raising an exception if one tries to access an unknown cell, instead of silently adding a new cell object with bogus default values.

**Comment by Gjum** [comment]
You are probably right. I used `defaultdict` to auto-create the cell in `parse_world_update`, but it would be cleaner if accessing non-existent cells raised an exception.
I will probably get around to change that today.

**Comment by Windfisch** [comment]
In particular, this got me on my agar.io bot Windfisch/agario-frickel@50921e339. This is a buggy commit, where the bot does not try to eat the next piece of food (denoted by a blue line, unless some enemies are making the bot escape; this would be denoted by a partly interrupted circle around your cell), but makes him go to (0,0) instead.

Windfisch/agario-frickel@1b71192eca047f8d fixes this, with the following diff

``` diff
     def on_cell_eaten(self, eater_id, eaten_id):
-        if self.c.world.cells[eater_id].is_virus:
+        if eater_id in self.c.world.cells and self.c.world.cells[eater_id].is_virus:
             print("virus ate something!")
+        
         if eater_id not in self.victims:
             self.victims[eater_id] = []
```

**Comment by Windfisch** [comment]
Also, I did not expect `on_cell_eaten()` to be fired for cells that aren't even in my viewport, which is probably worth a note in the documentation.

**Comment by Gjum** [comment]
Oh, when does that happen?

**Comment by Windfisch** [comment]
it seems to happen all the time, see Windfisch/agario-frickel@ebcc402492339

**Comment by Gjum** [comment]
Hmm, could you log the eater/eaten IDs?

**Comment by Windfisch** [comment]
Of course, but with what goal? I guess you need some world.cells dumps as well then?

**Comment by Gjum** [comment]
I remember noticing 0 as eater ID when I built the client, but have no idea what they mean.

**Comment by Gjum** [comment]
btw, do you want to join me on [Gitter](https://gitter.im/Gjum/gagar?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or IRC somewhere to discuss/debug this?
